### PR TITLE
Do real math for tempos

### PR DESCRIPTION
**Pull request by thedpws**

### CODE REVIEW

**Comment by thedpws** [comment]
Closes issue #12

**Comment by MenkeTechnologies** [comment]
are the tests passing?

**Comment by thedpws** [comment]
> are the tests passing?
No, they are not :( will update it the PR soon

**Comment by thedpws** [comment]
# actually
We don't have tests for the code I touched, so it shouldn't affect the tests passing. I'll look into why they are failing in the first place though.

**Pull request merged**
